gfx/env/fullmoonup.tga
gfx/env/fullmoondn.tga
gfx/env/fullmoonlf.tga
gfx/env/fullmoonrt.tga
gfx/env/fullmoonft.tga
gfx/env/fullmoonbk.tga
locs/agctf_dabo.loc
locs\agctf_dabo.loc
sound/ctf/blueflagreturned.wav
sound/ctf/blueflagstolen.wav
sound/ctf/blueleads.wav
sound/ctf/bluescores.wav
sound/ctf/enemyhaveflag.wav
sound/ctf/redflagreturned.wav
sound/ctf/redflagstolen.wav
sound/ctf/redleads.wav
sound/ctf/redscores.wav
sound/ctf/suddendeath.wav
sound/ctf/teamhaveflag.wav
sound/ctf/teamsaretied.wav
sound/ctf/youhaveflag.wav
