gfx/env/destbk.tga
gfx/env/destdn.tga
gfx/env/destft.tga
gfx/env/destlf.tga
gfx/env/destrt.tga
gfx/env/destup.tga
locs/dm_dust.loc
locs\dm_dust.loc
sound/ctf/blueflagreturned.wav
sound/ctf/blueflagstolen.wav
sound/ctf/blueleads.wav
sound/ctf/bluescores.wav
sound/ctf/enemyhaveflag.wav
sound/ctf/redflagreturned.wav
sound/ctf/redflagstolen.wav
sound/ctf/redleads.wav
sound/ctf/redscores.wav
sound/ctf/suddendeath.wav
sound/ctf/teamhaveflag.wav
sound/ctf/teamsaretied.wav
sound/ctf/youhaveflag.wav
