cstrike.wad
halflife.wad
decals.wad
itsitaly.wad
gfx/env/greenup.tga
gfx/env/greendn.tga
gfx/env/greenlf.tga
gfx/env/greenrt.tga
gfx/env/greenft.tga
gfx/env/greenbk.tga
sound/ambience/guit1.wav
sound/ambience/opera.wav
sound/misc/killchicken.wav
sound/misc/sheep.wav
sprites/flare1.spr
models/winebottle.mdl
models/chick.mdl
models/feather.mdl
locs/hlcs_italy.loc
sound/ctf/blueflagreturned.wav
sound/ctf/blueflagstolen.wav
sound/ctf/blueleads.wav
sound/ctf/bluescores.wav
sound/ctf/enemyhaveflag.wav
sound/ctf/redflagreturned.wav
sound/ctf/redflagstolen.wav
sound/ctf/redleads.wav
sound/ctf/redscores.wav
sound/ctf/suddendeath.wav
sound/ctf/teamhaveflag.wav
sound/ctf/teamsaretied.wav
sound/ctf/youhaveflag.wav
